# Config file for automatic testing at travis-ci.org

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        # these are just to make travis's UI a bit prettier
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox
